<?php

use App\Article;
use PHPUnit\Framework\TestCase;

class ArticleTest extends TestCase
{
    protected Article $article;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->article = new Article();
    }

    public function testTitleIsEmptyByDefault()
    {
        $this->assertEmpty($this->article->title);
    }

    public function testSlugIsEmptyWithNoTitle() {
        $this->assertSame($this->article->getSlug(), "");
    }

    public function testSlugHasSpacesReplacedByUnderscore() {
        $this->article->title = 'An example article';
        $this->assertEquals('An_example_article', $this->article->getSlug());
    }

    public function testSlugHasWhiteSpacesReplacedBySingleUnderscore() {
        $this->article->title = "An    example    \n  article";
        $this->assertEquals('An_example_article', $this->article->getSlug());
    }
}