<?php

use App\Item;
use App\ItemChild;
use PHPUnit\Framework\TestCase;

class ItemTest extends TestCase
{

    private Item $item;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->item = new Item();
    }

    public function testDescriptionIsNotEmpty() {
        $this->assertNotEmpty($this->item->getDescription());
    }

    public function testIdAnInteger() {
        $itemChild = new ItemChild();
        $this->assertIsInt($itemChild->getId());
    }

}